@api = http://localhost:3000/reservations

### get all products
GET {{api}}
### create a product
POST {{api}}
Content-Type: application/json

{
    "title": "Product 2",
    "description": "This is a product",
    "price": "100.00",
    "image": "http://www.example.com/image.jpg",
    "quantity": "10"
}

### get a single product by id
GET {{api}}/0123456789

### get a single product by id
GET {{api}}/0

### update a product by id
PUT {{api}}/631d4d0e5ace9408caf66b45
Content-Type: application/json

{
    "title": "Product 2",
    "description": "a second product",
    "price": "120.00"
}

### delete a product by id
DELETE {{api}}/631d4d0e5ace9408caf66b45